"""
simulator — MQTT stress-test simulator for the gateway translator.

Simulates 5 NORVI nodes publishing ModbusBridgePayload messages at a
rate of 15 messages/second (54,000 msg/h) to stress-test the E2E pipeline.

Execution is deferred until Docker/Nhost are available on the target
machine. See docs/adr/002-e2e-stress-test-deferred.md.
"""

import logging
import random
import time

import paho.mqtt.client as mqtt

# Protobuf stubs — generated by scripts/build_protos.sh
from telemetry_pb2 import ModbusBridgePayload, ModbusNodeState  # type: ignore[import-untyped]

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S%z",
)
logger = logging.getLogger("simulator")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
BROKER_HOST = "127.0.0.1"
BROKER_PORT = 1883
TOPIC = "novamex/linea1/telemetry"
TARGET_HZ = 15  # messages per second
SLEEP_INTERVAL = 1.0 / TARGET_HZ

# Simulated nodes
NODE_IDS = [f"norvi-node-{i}" for i in range(1, 6)]


def _build_payload(cycle: int) -> ModbusBridgePayload:
    """Build a ModbusBridgePayload with 5 virtual NORVI node states."""
    payload = ModbusBridgePayload()

    for node_id in NODE_IDS:
        node = payload.nodes.add()
        node.node_id = node_id
        node.cycle_count = cycle

        # Status: 1% probability of ERROR to test on_conflict mutations
        if random.random() < 0.01:
            node.status = 3  # ERROR
        else:
            node.status = 1  # RUNNING (= ONLINE)

    return payload


def main() -> None:
    client = mqtt.Client(
        callback_api_version=mqtt.CallbackAPIVersion.VERSION2,
        client_id="norvi-simulator",
    )

    try:
        client.connect(BROKER_HOST, BROKER_PORT, keepalive=60)
    except Exception:
        logger.exception(
            "Failed to connect to MQTT broker %s:%d", BROKER_HOST, BROKER_PORT
        )
        return

    client.loop_start()
    logger.info(
        "Simulator connected to %s:%d — publishing %d msg/s to %s",
        BROKER_HOST,
        BROKER_PORT,
        TARGET_HZ,
        TOPIC,
    )

    cycle = 0
    try:
        while True:
            cycle += 1
            payload = _build_payload(cycle)
            data = payload.SerializeToString()
            result = client.publish(TOPIC, data, qos=1)

            if result.rc == mqtt.MQTT_ERR_SUCCESS:
                logger.debug("Published cycle=%d (%d bytes)", cycle, len(data))
            else:
                logger.warning("Publish failed (rc=%s) cycle=%d", result.rc, cycle)

            time.sleep(SLEEP_INTERVAL)
    except KeyboardInterrupt:
        logger.info("Simulator stopped by user. Total cycles: %d", cycle)
    finally:
        client.loop_stop()
        client.disconnect()


if __name__ == "__main__":
    main()
