# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x10ibarra.telemetry\"j\n\x0fModbusNodeState\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ycle_count\x18\x02 \x01(\r\x12\x31\n\x06status\x18\x03 \x01(\x0e\x32!.ibarra.telemetry.OperatingStatus\"G\n\x13ModbusBridgePayload\x12\x30\n\x05nodes\x18\x01 \x03(\x0b\x32!.ibarra.telemetry.ModbusNodeState\"]\n\x15HardwareHealthPayload\x12\x17\n\x0f\x63pu_temperature\x18\x01 \x01(\x02\x12\x16\n\x0eram_used_bytes\x18\x02 \x01(\x04\x12\x13\n\x0bsystem_load\x18\x03 \x01(\x02*w\n\x0fOperatingStatus\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n\x0eSTATUS_RUNNING\x10\x01\x12\x12\n\x0eSTATUS_STOPPED\x10\x02\x12\x10\n\x0cSTATUS_ALARM\x10\x03\x12\x16\n\x12STATUS_MAINTENANCE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATINGSTATUS']._serialized_start=313
  _globals['_OPERATINGSTATUS']._serialized_end=432
  _globals['_MODBUSNODESTATE']._serialized_start=37
  _globals['_MODBUSNODESTATE']._serialized_end=143
  _globals['_MODBUSBRIDGEPAYLOAD']._serialized_start=145
  _globals['_MODBUSBRIDGEPAYLOAD']._serialized_end=216
  _globals['_HARDWAREHEALTHPAYLOAD']._serialized_start=218
  _globals['_HARDWAREHEALTHPAYLOAD']._serialized_end=311
# @@protoc_insertion_point(module_scope)
