# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry.proto
"""Generated protocol buffer code for telemetry.proto.

Defines the ModbusBridgePayload schema used by the gateway-translator
service. Reconstructed from the serialized FileDescriptorProto in the
original .pyc cache.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0ftelemetry.proto\x12\x10ibarra.telemetry"j\n\x0fModbusNodeState\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x13\n\x0bcycle_count\x18\x02 \x01(\r\x121\n\x06status\x18\x03 \x01(\x0e2!.ibarra.telemetry.OperatingStatus"G\n\x13ModbusBridgePayload\x120\n\x05nodes\x18\x01 \x03(\x0b2!.ibarra.telemetry.ModbusNodeState"]\n\x15HardwareHealthPayload\x12\x17\n\x0fcpu_temperature\x18\x01 \x01(\x02\x12\x16\n\x0eram_used_bytes\x18\x02 \x01(\x04\x12\x13\n\x0bsystem_load\x18\x03 \x01(\x02*w\n\x0fOperatingStatus\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n\x0eSTATUS_RUNNING\x10\x01\x12\x12\n\x0eSTATUS_STOPPED\x10\x02\x12\x10\n\x0cSTATUS_ALARM\x10\x03\x12\x16\n\x12STATUS_MAINTENANCE\x10\x04b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
