listener 1883 0.0.0.0
allow_anonymous true
persistence true
persistence_location /mosquitto/data/
autosave_interval 1800
connection_messages true
log_type information

# Secure listener requiring client mutual TLS (mTLS)
listener 8883 0.0.0.0
cafile /mosquitto/config/certs/ca.crt
certfile /mosquitto/config/certs/server.crt
keyfile /mosquitto/config/certs/server.key
require_certificate true
use_identity_as_username true

