# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\rmodbus_bridge\"b\n\x0fModbusNodeState\x12\x0f\n\x07node_id\x18\x01 \x01(\r\x12\x13\n\x0b\x63ycle_count\x18\x02 \x01(\r\x12)\n\x06status\x18\x03 \x01(\x0e\x32\x19.modbus_bridge.NodeStatus\"D\n\x13ModbusBridgePayload\x12-\n\x05nodes\x18\x01 \x03(\x0b\x32\x1e.modbus_bridge.ModbusNodeState*?\n\nNodeStatus\x12\x10\n\x0cNODE_OFFLINE\x10\x00\x12\x0f\n\x0bNODE_ONLINE\x10\x01\x12\x0e\n\nNODE_ERROR\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODESTATUS']._serialized_start=204
  _globals['_NODESTATUS']._serialized_end=267
  _globals['_MODBUSNODESTATE']._serialized_start=34
  _globals['_MODBUSNODESTATE']._serialized_end=132
  _globals['_MODBUSBRIDGEPAYLOAD']._serialized_start=134
  _globals['_MODBUSBRIDGEPAYLOAD']._serialized_end=202
# @@protoc_insertion_point(module_scope)
