// ============================================================================
// ota_builtin_key.h  —  Ed25519 public key embedded at build time
//
// Auto-generated by CI/CD pipeline via:
//   openssl pkey -in keys/ota-private-key.pem -pubout -out keys/ota-public-key.pem
//   xxd -i keys/ota-public-key.pem > src/ota_builtin_key.h
//
// This is the DEFAULT trust anchor.  At runtime, the key can be overridden
// by placing a new public key at /userdata/ota/trusted_keys/key-active.pub.
// ============================================================================

#ifndef OTA_BUILTIN_KEY_H
#define OTA_BUILTIN_KEY_H

#include <cstdint>

/// Ed25519 public key in PEM format (embedded fallback).
/// Replace this with the output of `xxd -i keys/ota-public-key.pem`.
static const uint8_t kOtaBuiltinPublicKey[] = {
    // Placeholder: generated Ed25519 public key in PEM format.
    // In production, replace with:  xxd -i keys/ota-public-key.pem
    0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x42, 0x45, 0x47, 0x49, 0x4e,
    0x20, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x20, 0x4b, 0x45,
    0x59, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x0a, 0x4d, 0x43, 0x6f,
    0x77, 0x42, 0x51, 0x59, 0x44, 0x4b, 0x44, 0x32, 0x56, 0x41,
    0x77, 0x45, 0x68, 0x0a, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x45,
    0x4e, 0x44, 0x20, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x20,
    0x4b, 0x45, 0x59, 0x2d, 0x2d, 0x2d, 0x2d, 0x2d, 0x0a
};
// Length is derived via sizeof() at the usage site to stay in sync.

#endif // OTA_BUILTIN_KEY_H
